
title: <p align="center"> BE </p>

logo: "/assets/IMG-20220225-WA0092-modified.png"

description:
  <p align="center">
  paris,France
 <a href='mailto:bargaouiemnaaa@gmail.com'>GMAIL</a>|
  <a href="https://github.com/brgE-93">GitHub</a> 
  </p>
theme: jekyll-theme-minimal

