logo: "/assets/IMG-20220225-WA0092-modified.png"
title:<p align="center"> B_Emna </p>

description:
  <p align="center">
  paris,France<br>

  
 <a href='mailto:bargaouiemnaaa@gmail.com'>GMAIL</a>|
  <a href="https://github.com/brgE-93">GitHub</a> 
  </p>
comments:
provider : false
theme: jekyll-theme-minimal

